// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDddgPath() {
  return window['go']['main']['App']['GetDddgPath']();
}

export function GetPacks() {
  return window['go']['main']['App']['GetPacks']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MountPack(arg1) {
  return window['go']['main']['App']['MountPack'](arg1);
}

export function TriggerCoreStateUpdate() {
  return window['go']['main']['App']['TriggerCoreStateUpdate']();
}

export function UpdateDddgPath() {
  return window['go']['main']['App']['UpdateDddgPath']();
}

export function UploadFile(arg1, arg2) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2);
}
