// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Alert(arg1, arg2) {
  return window['go']['main']['App']['Alert'](arg1, arg2);
}

export function Confirm(arg1, arg2) {
  return window['go']['main']['App']['Confirm'](arg1, arg2);
}

export function CreatePack(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreatePack'](arg1, arg2, arg3);
}

export function GetDddgPath() {
  return window['go']['main']['App']['GetDddgPath']();
}

export function GetPacks() {
  return window['go']['main']['App']['GetPacks']();
}

export function GetRepoJson() {
  return window['go']['main']['App']['GetRepoJson']();
}

export function MountPack(arg1) {
  return window['go']['main']['App']['MountPack'](arg1);
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function TriggerCoreStateUpdate() {
  return window['go']['main']['App']['TriggerCoreStateUpdate']();
}

export function UpdateDddgPath() {
  return window['go']['main']['App']['UpdateDddgPath']();
}

export function UploadFile(arg1, arg2) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2);
}
