// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDddgPath():Promise<string>;

export function GetPacks():Promise<Array<main.Pack>>;

export function Greet(arg1:string):Promise<string>;

export function MountPack(arg1:string):Promise<void>;

export function TriggerCoreStateUpdate():Promise<void>;

export function UpdateDddgPath():Promise<void>;
